#!/usr/bin/env bash

CRITICAL="$1"
WARNING="$2"

if [ "$(cat /proc/cpuinfo  | egrep '^Model' | cut -d':' -f2 | sed -E 's/^\ //g')" == 'Raspberry Pi 4 Model B Rev 1.4' ] || \
   [ "$(cat /proc/cpuinfo  | egrep '^Model' | cut -d':' -f2 | sed -E 's/^\ //g')" == 'Raspberry Pi 3 Model B Plus Rev 1.3' ]; then
    TEMP=$(sensors -f | grep 'temp1:' | awk '{print $2}' | sed 's/+//g')

else
    TEMP=$(sensors -f | egrep '^Core 0:' | awk '{print $3}' | sed 's/+//g')

fi

if [ "${TEMP}" -ge "${CRITICAL}" ]; then
    echo "CRITICAL - cpu temperature : ${TEMP} F"
    exit 2

elif [ "${TEMP}" -ge "${WARNING}" ] && \
     [ "${TEMP}" -lt "${CRITICAL}" ]; then
    echo "WARNING - cpu temperature : ${TEMP} F"
    exit 1

else
    echo "OK - cpu temperature : ${TEMP} F"
    exit 0

fi
