#!/usr/bin/env bash

DEPLOYMENT="$1"
SERVICE="$2"

if [ "${DEPLOYMENT}" == 'acme' ]; then
    url='http://labs.elysianskies.com'
    SERVICE='apache'

elif [ "${DEPLOYMENT}" == 'bigbrother' ]; then
    url='https://labs.elysianskies.com/zm/'
    SERVICE='zoneminder'

elif [ "${DEPLOYMENT}" == 'filebrowser' ]; then
    url='https://labs.elysianskies.com/tvault'
    SERVICE='apache'

elif [ "${DEPLOYMENT}" == 'kharon' ] && [ "${SERVICE}" == 'expressvpn' ]; then
    url='http://kube00.labs.elysianskies.com:3128'
    http_response_proxy=$(curl -s ifconfig.me -x $url)
    http_response_local=$(curl -s ifconfig.me)

    if [ "$http_response_proxy" == "$http_response_local" ] \
        || [ -z "$http_response_proxy" ]; then
        echo "CRITICAL - wan ip exposed : $http_response_local"
        exit 2

    else
        echo "OK - expressvpn wan ip : $http_response_proxy"
        exit 0

    fi

elif [ "${DEPLOYMENT}" == 'kharon' ] && [ "${SERVICE}" == 'squid' ]; then
    url='http://kube00.labs.elysianskies.com:3128'

    if [ $(curl -s -k -i $url | egrep '^Server:' | awk '{print $2}' | cut -d'/' -f1) == 'squid' ]; then
        echo "OK - squid proxy detected - $url"
        exit 0

    else
        echo "CRITICAL - no squid proxy found - $url"
        exit 2

    fi

elif [ "${DEPLOYMENT}" == 'kharon' ] && [ "${SERVICE}" == 'deluge' ]; then
    url='https://labs.elysianskies.com/deluge'

elif [ "${DEPLOYMENT}" == 'plex' ] && [ "${SERVICE}" == 'plexserver' ]; then
    url='https://labs.elysianskies.com:32400/web'

elif [ "${DEPLOYMENT}" == 'plex' ] && [ "${SERVICE}" == 'tautulli' ]; then
    url='https://labs.elysianskies.com/tautulli'

fi

http_response=$(curl -siLk $url | egrep ^HTTP\/ | tail -1 | awk '{print $2}')

if [ "$http_response" == '200' ]; then
    echo "OK - $http_response ${DEPLOYMENT}/${SERVICE} - $url"
    exit 0

else
    echo "CRITICAL - $http_response ${DEPLOYMENT}/${SERVICE} - $url"
    exit 2

fi
