alias eslabs_deploy="${ELISE_ROOT_DIR}/scripts/eslabs.sh deploy"
alias eslabs_destroy="${ELISE_ROOT_DIR}/scripts/eslabs.sh destroy"
alias eslabs_nuke="countdown_to_cmd \"${ELISE_ROOT_DIR}/scripts/eslabs.sh stop; ${ELISE_ROOT_DIR}/scripts/eslabs.sh destroy yes; ${ELISE_ROOT_DIR}/scripts/eslabs.sh deploy\""
alias eslabs_shutdown="${ELISE_ROOT_DIR}/scripts/eslabs.sh shutdown"
alias eslabs_stop="${ELISE_ROOT_DIR}/scripts/eslabs.sh stop"
