KUBE_AUTOMATOR="${ELISE_ROOT_DIR}/scripts/kube_automator.sh"

# kubernetes - manifests
alias k_manifest_apply="kube_manifest apply"
alias k_manifest_delete="kube_manifest delete"
alias k_manifest_diff="kube_manifest diff"
alias k_manifest_edit="kube_manifest edit"
alias k_manifest_list="ls -m1 ${ELISE_ROOT_DIR}/manifests | cut -d'.' -f1"

# kubernetes - general
alias k_crash="${KUBE_AUTOMATOR} crash"
alias k_describe="${KUBE_AUTOMATOR} describe"
alias k_display="${KUBE_AUTOMATOR} display"
alias k_edit="${KUBE_AUTOMATOR} edit"
alias k_exec="${KUBE_AUTOMATOR} exec"
alias k_get="${KUBE_AUTOMATOR} get"
alias k_logs="${KUBE_AUTOMATOR} logs"
alias k_nodes="${KUBE_AUTOMATOR} nodes"
alias k_restart="${KUBE_AUTOMATOR} restart"
alias k_shell="${KUBE_AUTOMATOR} shell"
alias k_start="${KUBE_AUTOMATOR} start"
alias k_stop="${KUBE_AUTOMATOR} stop"
alias k_tail="${KUBE_AUTOMATOR} tail"

# kubernetes - kube-system namespace
alias k_system_describe="${KUBE_AUTOMATOR} describe kube-system"
alias k_system_display="${KUBE_AUTOMATOR} display kube-system"
alias k_system_events="${KUBE_AUTOMATOR} get kube-system events"
alias k_system_get="${KUBE_AUTOMATOR} get kube-system"
alias k_system_tail="${KUBE_AUTOMATOR} tail kube-system"
alias k_system_watch="while true; do clear; ${KUBE_AUTOMATOR} display kube-system; sleep 5; done"

# kubernetes - ingress-nginx namespace
alias k_ingress_describe="${KUBE_AUTOMATOR} describe ingress-nginx"
alias k_ingress_display="${KUBE_AUTOMATOR} display ingress-nginx"
alias k_ingress_events="${KUBE_AUTOMATOR} get ingress-nginx events"
alias k_ingress_get="${KUBE_AUTOMATOR} get ingress-nginx"
alias k_ingress_tail="${KUBE_AUTOMATOR} tail ingress-nginx"
alias k_ingress_watch="while true; do clear; ${KUBE_AUTOMATOR} display ingress-nginx; sleep 5; done"

# kubernetes - eslabs namespace
alias k_eslabs_crash="${KUBE_AUTOMATOR} crash eslabs"
alias k_eslabs_crash_kharon_deluge="${KUBE_AUTOMATOR} crash eslabs kharon deluge"
alias k_eslabs_crash_kharon_squid="${KUBE_AUTOMATOR} crash eslabs kharon squid"
alias k_eslabs_describe="${KUBE_AUTOMATOR} describe eslabs"
alias k_eslabs_display="${KUBE_AUTOMATOR} display eslabs"
alias k_eslabs_edit="${KUBE_AUTOMATOR} edit eslabs"
alias k_eslabs_events="${KUBE_AUTOMATOR} get eslabs events"
alias k_eslabs_exec="${KUBE_AUTOMATOR} exec eslabs"
alias k_eslabs_get="${KUBE_AUTOMATOR} get eslabs"
alias k_eslabs_logs="${KUBE_AUTOMATOR} logs eslabs"
alias k_eslabs_restart="${KUBE_AUTOMATOR} restart eslabs"
alias k_eslabs_shell="${KUBE_AUTOMATOR} shell eslabs"
alias k_eslabs_start="${KUBE_AUTOMATOR} start eslabs"
alias k_eslabs_stop="${KUBE_AUTOMATOR} stop eslabs"
alias k_eslabs_tail="${KUBE_AUTOMATOR} tail eslabs"
alias k_eslabs_watch="while true; do clear; ${KUBE_AUTOMATOR} display eslabs; sleep 5; done"
