- hosts: "~(rpi|worker_nodes)"
  become: true
  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: set cron values
      cron:
        name: "{{ item.key }}"
        env: yes
        value: "{{ item.value }}"
      with_items:
        - key: SHELL
          value: /bin/bash
        - key: MAILTO
          value: root
        - key: PATH
          value: /sbin:/bin:/usr/sbin:/usr/bin
        - key: ELISE_ROOT_DIR
          value: /mnt/tvault/es-labs/projects/elise
      notify: systemctl restart cron
