- hosts: kube02.labs.elysianskies.com
  gather_facts: false
  become: true
  vars:
    ELISE_ROOT_DIR: /tmp/lab_backup

  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: cronjob - lab_backup - variables
      cron:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        env: yes
      with_items:
        - name: SHELL
          value: /bin/bash
        - name: PATH
          value: /sbin:/bin:/usr/sbin:/usr/bin
        - name: MAILTO
          value: root
        - name: ELISE_ROOT_DIR
          value: "{{ ELISE_ROOT_DIR }}"
      notify: systemctl restart cron

    - name: cronjob - lab_backup - job
      cron:
        name: lab_backup
        minute: '0'
        hour: '17'
        weekday: '2'
        user: root
        job: "${ELISE_ROOT_DIR}/scripts/lab_backup.sh >> /mnt/tvault/es-labs/backups/iscsi_volumes/backup_cron.log"
      notify: systemctl restart cron

- hosts: worker_nodes
  gather_facts: false
  become: true
  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: cronjob - ssl_renew - variables
      cron:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        env: yes
      with_items:
        - name: SHELL
          value: /bin/bash
        - name: PATH
          value: /sbin:/bin:/usr/sbin:/usr/bin
        - name: MAILTO
          value: root
      notify: systemctl restart cron

    - name: cronjob - ssl_renew - job
      cron:
        name: ssl_renew
        minute: '0'
        hour: '0'
        day: '1'
        month: '2,4,6,8,10,12'
        user: root
        job: docker exec -it $(docker ps | egrep -o 'k8s_acme_acme-.*$') certbot renew
      notify: systemctl restart cron
