###########################################
# global cron variables
###########################################

- hosts: k8s
  become: true
  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: crontab variables
      cron:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        env: yes
      with_items:
        - name: SHELL
          value: /bin/bash
        - name: PATH
          value: /sbin:/bin:/usr/sbin:/usr/bin
        - name: MAILTO
          value: root
        - name: ELISE_ROOT_DIR
          value: /usr/elise
      notify: systemctl restart cron

###########################################
# cron - soteria
###########################################

- hosts: kube02.labs.elysianskies.com
  become: true
  vars:
    log_dir: /mnt/tvault/es-labs/logs
    cron_name: soteria
    cron_cmd: ${ELISE_ROOT_DIR}/scripts/soteria.sh

  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: "cronjob - {{ cron_name }} - job"
      cron:
        name: "{{ cron_name }}"
        minute: '20'
        hour: '4'
        weekday: '3'
        user: root
        job: "{{ cron_cmd }} >> {{ log_dir }}/{{ cron_name }}-$(hostname).log"
      notify: systemctl restart cron

###########################################
# cron - ssl_renew
###########################################

- hosts: worker_nodes
  become: true
  vars:
    log_dir: /mnt/tvault/es-labs/logs
    cron_name: ssl_renew
    cron_cmd: docker exec $(docker ps | egrep -o 'k8s_hermes_hermes-.*$') /tmp/certbot.sh renew

  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: "cronjob - {{ cron_name }} - job"
      cron:
        name: "{{ cron_name }}"
        minute: '0'
        hour: '4'
        day: '*/89'
        user: root
        job: "{{ cron_cmd }} >> {{ log_dir }}/{{ cron_name }}-$(hostname).log"
      notify: systemctl restart cron

###########################################
# cron - haproxy_restart
###########################################

- hosts: master_node
  become: true
  vars:
    log_dir: /mnt/tvault/es-labs/logs
    cron_name: haproxy_restart
    cron_cmd: docker restart haproxy

  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: "cronjob - {{ cron_name }} - job"
      cron:
        name: "{{ cron_name }}"
        minute: '10'
        hour: '4'
        day: '*/89'
        user: root
        job: "{{ cron_cmd }} >> {{ log_dir }}/{{ cron_name }}-$(hostname).log"
      notify: systemctl restart cron
