- hosts: k8s
  gather_facts: false
  become: true
  handlers:
    - name: systemctl restart docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

  tasks:
    - name: install packages that allow apt to be used over https
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: add an apt signing key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add apt repository for stable version
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        update_cache: yes
        state: present

    - name: install docker and its dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify: systemctl restart docker

    - name: configure docker cgroup driver
      copy:
        src: ../../files/docker/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
      notify: systemctl restart docker

    - name: configure docker service
      service:
        name: docker
        enabled: yes
        state: started

- hosts: master_node
  gather_facts: false
  become: true
  tasks:
    # needed so ansible can deploy containers
    # via the docker_container module
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - python3-pip

    - name: install python packages
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
          - docker
