- hosts: ubuntu
  gather_facts: false
  become: true
  tasks:
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - net-tools
          - bc
          - htop
          - vim
