- hosts: ubuntu
  become: true
  tasks:
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - net-tools
          - bc
          - python3-pip

    - name: install python packages
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
          - docker
