- hosts: "~(rpi|worker_nodes)"
  become: true
  tasks:
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - net-tools
          - bc
          - htop
          - vim
          - cron
          - jq

    - name: configure general services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - cron

- hosts: rpi
  become: true
  tasks:
    - name: disable wireless interfaces
      shell: iwconfig wlan0 txpower off
