- hosts: ubuntu
  gather_facts: false
  become: true
  tasks:
    - name: install apt packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - net-tools
          - bc
          - htop
          - vim
          - cron

    - name: configure general services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - cron
