- hosts: ubuntu
  become: true
  tasks:
    - name: install packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - net-tools
