- hosts: master_node
  gather_facts: false
  become: true
  tasks:
    - name: import haproxy.cfg
      shell: cat ../../files/haproxy.cfg
      delegate_to: localhost
      register: haproxy_cfg

    - name: configure haproxy container
      docker_container:
        image: haproxy:latest
        name: haproxy
        state: "{{ container_state }}"
        recreate: "{{ recreate_container }}"
        command: |
          /bin/bash -c '\
            cat /etc/letsencrypt/live/labs.elysianskies.com/fullchain.pem > /usr/local/etc/haproxy/nginx.pem; \
            cat /etc/letsencrypt/live/labs.elysianskies.com/privkey.pem >> /usr/local/etc/haproxy/nginx.pem; \
            echo "{{ haproxy_cfg.stdout }}" > /usr/local/etc/haproxy/haproxy.cfg; \
            chmod 640 /usr/local/etc/haproxy/nginx.pem; \
            chmod 755 /usr/local/etc/haproxy/haproxy.cfg; \
            haproxy -f /usr/local/etc/haproxy/haproxy.cfg'
        volumes:
          - /mnt/tvault/es-labs/letsencrypt:/etc/letsencrypt
        ports:
          - '443:443'
          - '80:80'
        network_mode: bridge
        restart_policy: unless-stopped
