- hosts: master_node
  become: true
  tasks:
    - name: import haproxy.cfg
      shell: |
        source ../../files/haproxy.cfg.sh;
        echo "${HAPROXY_CFG}"
      delegate_to: localhost
      register: haproxy_cfg

    - name: "{{ message }} haproxy container"
      docker_container:
        image: haproxy:latest
        name: haproxy
        state: "{{ container_state }}"
        recreate: "{{ recreate_container }}"
        # enable these sysctls to prevent syn-flood type attacks
        sysctls:
          net.ipv4.tcp_syncookies: 1
          net.ipv4.conf.all.rp_filter: 1
          net.ipv4.tcp_max_syn_backlog: 1024
        command: |
          /bin/bash -c '\
            echo "{{ haproxy_cfg.stdout }}" > /tmp/haproxy.cfg; \
            chmod 755 /tmp/haproxy.cfg; \
            haproxy -f /tmp/haproxy.cfg'
        ports:
          - '443:443'
          - '80:80'
          - '32401:32400'
          - '3128:3128'
        volumes:
          - '/mnt/tvault/es-labs/ssl:/usr/local/etc/haproxy/ssl'
        network_mode: bridge
        restart_policy: unless-stopped
      ignore_errors: yes
