- hosts: master_node
  become: true
  tasks:

    - name: import elise.sh vars
      shell: |
        source ../../src/elise.sh
        echo "${LAB_FQDN}"
      no_log: true
      register: lab_fqdn_var

    # pod-network-cidr MUST match the Network element in net-conf.json in the
    # kube-flannel deployment
    - name: initialize kubernetes cluster
      shell: |
        kubeadm init \
          --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" \
          --pod-network-cidr="10.244.0.0/16" \
          --apiserver-cert-extra-sans="{{ lab_fqdn_var.stdout }}"

    - name: setup kubeconfig
      shell: "{{ item }}"
      with_items:
        - mkdir -p {{ ansible_env.HOME }}/.kube
        - cp -i /etc/kubernetes/admin.conf {{ ansible_env.HOME }}/.kube/config
        - chown $(id -u):$(id -g) {{ ansible_env.HOME }}/.kube/config

    - name: deploy flannel pod network
      shell: /root/manifests/kube-flannel.sh apply

    - name: deploy nginx ingress controller
      shell: /root/manifests/ingress-nginx.sh apply

    - name: generate join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: copy join command to local file
      copy:
        content: "{{ join_command.stdout_lines[0] }}"
        dest: /tmp/join-command
      delegate_to: localhost

- hosts: worker_nodes
  become: true
  tasks:
    - name: copy the join command to server location
      copy:
        src: /tmp/join-command
        dest: /tmp/join-command.sh
        mode: 0777

    - name: join nodes to cluster
      shell: "sh /tmp/join-command.sh"
    
    - name: cleanup join-command on worker_nodes
      file:
        path: /tmp/join-command.sh
        state: absent

    - name: cleanup join-command on localhost
      file:
        path: /tmp/join-command
        state: absent
      delegate_to: localhost
