- hosts: k8s
  become: true
  tasks:
    - name: kubeadm reset
      shell: kubeadm reset -f
      ignore_errors: yes

    - name: remove kubernetes and docker binaries
      apt:
        name: "{{ packages }}"
        state: absent
        purge: yes
        force: yes
        autoremove: yes
        autoclean: yes
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: cleanup
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ ansible_env.HOME }}/.kube"
        - /etc/kubernetes
        - /var/lib/kubelet
        - /usr/libexec/kubernetes
        - /var/log/pods
        - /etc/systemd/system/kubelet.service
        - /etc/systemd/system/kubelet.service.d
        - /var/lib/systemd/deb-systemd-helper-masked/kubelet.service
        - /var/lib/systemd/deb-systemd-helper-enabled/kubelet.service.dsh-also
        - /var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/kubelet.service
        - /etc/default/kubelet
        - /etc/cni
        - /etc/docker
        - /usr/libexec/docker
        - /var/lib/docker
        - /var/lib/dockershim

    - name: reload systemd
      shell: "{{ item }}"
      with_items:
        - systemctl daemon-reload
        - systemctl reset-failed

    - name: reset all iptables
      shell: "{{ item }}"
      with_items:
        - iptables --table filter --policy INPUT ACCEPT
        - iptables --table filter --policy OUTPUT ACCEPT
        - iptables --table filter --policy FORWARD ACCEPT
        - iptables --table filter --zero
        - iptables --table filter --flush
        - iptables --table filter --delete-chain
        - iptables --table nat --policy PREROUTING ACCEPT
        - iptables --table nat --policy INPUT ACCEPT
        - iptables --table nat --policy POSTROUTING ACCEPT
        - iptables --table nat --policy OUTPUT ACCEPT
        - iptables --table nat --zero
        - iptables --table nat --flush
        - iptables --table nat --delete-chain
        - iptables --table mangle --policy PREROUTING ACCEPT
        - iptables --table mangle --policy INPUT ACCEPT
        - iptables --table mangle --policy FORWARD ACCEPT
        - iptables --table mangle --policy OUTPUT ACCEPT
        - iptables --table mangle --policy POSTROUTING ACCEPT
        - iptables --table mangle --zero
        - iptables --table mangle --flush
        - iptables --table mangle --delete-chain
        - iptables --table security --policy INPUT ACCEPT
        - iptables --table security --policy OUTPUT ACCEPT
        - iptables --table security --policy FORWARD ACCEPT
        - iptables --table security --zero
        - iptables --table security --flush
        - iptables --table security --delete-chain
        - iptables --table raw --policy PREROUTING ACCEPT
        - iptables --table raw --policy OUTPUT ACCEPT
        - iptables --table raw --zero
        - iptables --table raw --flush
        - iptables --table raw --delete-chain
