- hosts: master_node
  become: true
  tasks:
    - name: generate join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: copy join command to local file
      copy:
        content: "{{ join_command.stdout_lines[0] }}"
        dest: /tmp/join-command
      delegate_to: localhost

- hosts: worker_nodes
  become: true
  tasks:
    - name: copy the join command to server location
      copy:
        src: /tmp/join-command
        dest: /tmp/join-command.sh
        mode: 0777

    - name: join nodes to cluster
      shell: "sh /tmp/join-command.sh"
    
    - name: cleanup join-command on worker_nodes
      file:
        path: /tmp/join-command.sh
        state: absent

    - name: cleanup join-command on localhost
      file:
        path: /tmp/join-command
        state: absent
      delegate_to: localhost
