- hosts: kube02.labs.elysianskies.com
  gather_facts: false
  become: true
  vars:
    ELISE_ROOT_DIR: /tmp/lab_backup

  environment:
    ELISE_ROOT_DIR: "{{ ELISE_ROOT_DIR }}"

  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: ensure lab_backup dir
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0750
      when: option == "copy"
      with_items:
        - "{{ ELISE_ROOT_DIR }}"
        - "{{ ELISE_ROOT_DIR }}/src"
        - "{{ ELISE_ROOT_DIR }}/scripts"

    - name: import lab_backup vars from localhost elise.sh
      shell: "egrep ^{{ item }} ../../src/elise.sh"
      register: elise_vars
      when: option == "copy"
      delegate_to: localhost
      with_items:
        - ISCSI_CHAP_SESSION_USERNAME
        - ISCSI_CHAP_SESSION_PASSWORD
        - ISCSI_CRON_HOST
        - ISCSI_PORTAL
        - ISCSI_LOCAL_MOUNT_DIR
        - ISCSI_BACKUP_DIR
        - ISCSI_IQN
        - ISCSI_BACKUP_VOLUMES -A6
        - KUBE_CONFIG_FILE

    - name: reset remote elise.sh vars
      file:
        path: "{{ ELISE_ROOT_DIR }}/src/elise.sh"
        state: absent
      when: option == "copy"

    - name: generate new remote elise.sh vars
      shell: echo '{{ item.stdout }}' >> {{ ELISE_ROOT_DIR }}/src/elise.sh
      no_log: true
      when: option == "copy"
      with_items:
        - "{{ elise_vars.results }}"

    - name: copy source files
      copy:
        src: "../../{{ item }}"
        dest: "{{ ELISE_ROOT_DIR }}/{{ item }}"
        owner: root
        group: root
        mode: 0750
      when: option == "copy"
      with_items:
        - scripts/lab_backup.sh
        - src/colors.sh
        - src/general.sh
        - src/iscsi.sh
        - src/kubernetes.sh

    - name: configure crontab - variables
      cron:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        env: yes
      with_items:
        - name: SHELL
          value: /bin/bash
        - name: PATH
          value: /sbin:/bin:/usr/sbin:/usr/bin
        - name: MAILTO
          value: root
        - name: ELISE_ROOT_DIR
          value: "{{ ELISE_ROOT_DIR }}"
      notify: systemctl restart cron
      when: option == "copy"

    - name: configure crontab - job
      cron:
        name: lab_backup
        minute: '0'
        hour: '4'
        weekday: '3'
        user: root
        job: "${ELISE_ROOT_DIR}/scripts/lab_backup.sh >> /mnt/tvault/es-labs/backups/iscsi_volumes/backup_cron.log"
      notify: systemctl restart cron
      when: option == "copy"

    - name: execute lab_backup tasks
      shell: "{{ ELISE_ROOT_DIR }}/scripts/lab_backup.sh"
      register: backup_output
      when: option == "execute"

    - debug: var=backup_output.stdout_lines
      when: option == "execute"

    - name: remove lab_backup
      file:
        path: "{{ item }}"
        state: absent
        owner: root
        group: root
        mode: 0750
      when: option == "remove"
      with_items:
        - "{{ ELISE_ROOT_DIR }}"
        - /root/.kube
