- hosts: "~(rpi|worker_nodes)"
  gather_facts: false
  become: true
  handlers:
    - name: systemctl restart nagios-nrpe
      systemd:
        name: nagios-nrpe
        state: restarted

  tasks:
    - name: copy nrpe.cfg
      copy:
        src: ../../files/nagios/nrpe.cfg
        dest: /etc/nagios/nrpe.cfg
        owner: root
        group: root
        mode: 0644
      notify: systemctl restart nagios-nrpe

    - name: install nrpe binaries
      apt:
        name:
        state: present
        update_cache: yes
      vars:
        packages:
          - monitoring-plugins
          - nagios-nrpe-plugin
          - nagios-nrpe-server

    - name: configure nagios-nrpe service
      systemd:
        name: nagios-nrpe
        state: started
        enabled: true
