- hosts: nrpe
  gather_facts: true
  become: true
  handlers:
    - name: systemctl restart nagios-nrpe-server
      systemd:
        name: nagios-nrpe-server
        state: restarted
        daemon_reload: yes

  tasks:
    - name: install nrpe binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - nagios-nrpe-server
          - nagios-nrpe-plugin
          - monitoring-plugins
          - lm-sensors

    - name: configure nagios-nrpe-server service
      systemd:
        name: nagios-nrpe-server
        state: started
        daemon_reload: yes
        enabled: true

    - name: copy nrpe.cfg
      template:
        src: ../../files/nagios/nrpe.cfg
        dest: /etc/nagios/nrpe.cfg
        owner: root
        group: root
        mode: 0644
      notify: systemctl restart nagios-nrpe-server

    - name: copy custom plugins
      copy:
        src: "../../files/nagios/{{ item }}"
        dest: "/usr/lib/nagios/plugins/{{ item }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - check_mem
        - check_int
        - check_temp
        - check_k8s
