- hosts: netmon
  become: true
  vars:
    ntopng_package: apt-ntop_1.0.190416-469_all.deb

  handlers:
    - name: systemctl restart ntopng
      systemd:
        name: ntopng
        state: restarted
        daemon_reload: yes

  tasks:
    - name: import ntopng license
      shell: |
        source ../../src/elise.sh;
        echo "${NTOPNG_LICENSE}"
      delegate_to: localhost
      register: ntopng_license

    - name: download ntopng apt raspbian repo
      get_url:
        url: "https://packages.ntop.org/RaspberryPI/{{ ntopng_package }}"
        dest: "/tmp/{{ ntopng_package }}"
        mode: 0750

    - name: install ntopng repo
      apt:
        deb: "/tmp/{{ ntopng_package }}"
        state: present
        update_cache: yes

    - name: install ntopng packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - ntopng
          - nprobe
          - n2n

    - name: ensure web root configuration
      lineinfile:
        path: /etc/ntopng/ntopng.conf
        line: --http-prefix="/ntopng"
      notify: systemctl restart ntopng

    - name: ensure ntopng license
      copy:
        content: "{{ ntopng_license.stdout }}"
        dest: /etc/ntopng.license
      notify: systemctl restart ntopng

    - name: configure ntopng service
      systemd:
        name: ntopng
        enabled: yes
        state: started
