- hosts: netmon
  gather_facts: false
  become: true
  tasks:
    - name: configure ntopng container
        image: ntop/ntopng:stable
        name: ntopng
        state: started
        ports:
          - '3000:3000'
        network_mode: host
        # volumes:
        #   - /mnt/tvault/es-labs/haproxy:/usr/local/etc/haproxy
        restart_policy: unless-stopped
        interactive: yes
        tty: yes
        command: -i eth0
