- hosts: pihole
  become: true
  tasks:
  - name: download pihole installer
    get_url:
      url: https://install.pi-hole.net
      dest: /tmp/install-pihole.sh
      mode: 0755

  - name: ensure pihole configuration directory
    file:
      path: /etc/pihole
      state: directory
      owner: root
      group: root
      mode: 0755
    become: yes

  - name: copy pihole configurations
    copy:
      src: ../files/{{ item }}
      dest: /etc/pihole/{{ item }}
      owner: root
      group: root
      mode: 0644
    become: yes
    with_items:
      - setupVars.conf
      - custom.list

  - name: install pihole
    shell: "/tmp/install-pihole.sh --unattended"
    become: yes
    register: result

  - debug: var=result.stdout_lines
