- hosts: kube02.labs.elysianskies.com
  become: true
  vars:
    ELISE_ROOT_DIR: /usr/elise

  environment:
    ELISE_ROOT_DIR: "{{ ELISE_ROOT_DIR }}"

  tasks:
    - block:
      - name: ensure soteria dir
        file:
          path: "{{ item }}"
          state: directory
          owner: root
          group: root
          mode: 0750
        with_items:
          - "{{ ELISE_ROOT_DIR }}"
          - "{{ ELISE_ROOT_DIR }}/src"
          - "{{ ELISE_ROOT_DIR }}/scripts"

      - name: copy source files
        copy:
          src: "../../{{ item }}"
          dest: "{{ ELISE_ROOT_DIR }}/{{ item }}"
          owner: root
          group: root
          mode: 0750
        with_items:
          - scripts/soteria.sh
          - src/elise.sh
          - src/general.sh
          - src/iscsi.sh
          - src/kubernetes.sh
      when: option == "deploy"

    - block:
      - name: execute soteria tasks
        shell: "{{ ELISE_ROOT_DIR }}/scripts/soteria.sh"
        register: backup_output

      - debug: var=backup_output.stdout_lines
      when: option == "execute"

    - name: remove soteria
      file:
        path: "{{ item }}"
        state: absent
        owner: root
        group: root
        mode: 0750
      with_items:
        - "{{ ELISE_ROOT_DIR }}"
        - /root/.kube
      when: option == "remove"
