- hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: generate new certificate
      shell: |
        kubectl -n eslabs exec --stdin --tty \
            "$(kubectl -n eslabs get pods | egrep -o '^acme-[0-9a-z]{1,}-[0-9a-z]{1,}')" -- \
            /bin/bash -c 'rm -rf /etc/letsencrypt/*; /tmp/certbot.sh generate'
      register: generate_new_certificate
      when: option == "generate"

    - name: display current certificate
      shell: |
        kubectl -n eslabs exec --stdin --tty \
            "$(kubectl -n eslabs get pods | egrep -o '^acme-[0-9a-z]{1,}-[0-9a-z]{1,}')" -- \
            /bin/bash -c '/tmp/certbot.sh display'
      register: display_current_certificate
      when: option == "display"

    - debug: var=display_current_certificate.stdout_lines
      when: option == "display"

    - debug: var=generate_new_certificate.stdout_lines
      when: option == "generate"
