- hosts: kube02.labs.elysianskies.com  # worker where `acme` pod is deployed
  gather_facts: false
  become: true
  handlers:
    - name: systemctl restart cron
      systemd:
        name: cron
        state: restarted
        daemon_reload: yes

  tasks:
    - name: import ssl directory
      shell: egrep '^LAB_SSL_DIR=' ../../src/elise.sh | cut -d"'" -f2
      delegate_to: localhost
      register: ssl_dir

    - name: configure crontab - variables
      cron:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        env: yes
      with_items:
        - name: SHELL
          value: /bin/bash
        - name: PATH
          value: /sbin:/bin:/usr/sbin:/usr/bin
        - name: MAILTO
          value: root
      notify: systemctl restart cron

    - name: configure crontab - job
      cron:
        name: ssl_renew
        month: '2,4,6,8,10,12'
        user: root
        job: "docker exec -it $(docker ps | egrep -o 'k8s_acme_acme-.*$') certbot renew >> {{ ssl_dir.stdout }}/certbot_renew.log"
      notify: systemctl restart cron
