- hosts: watchers
  become: true
  vars_prompt:
    - name: watcher_username
      prompt: enter rtsp username
      private: no

    - name: watcher_password
      prompt: enter rtsp password
      private: yes

  tasks:
    - name: configure webcams
      shell: |
        v4l2-ctl -d {{ item }} --set-ctrl=led1_mode=0
        v4l2-ctl -d {{ item }} --set-ctrl=sharpness=255
        v4l2-ctl -d {{ item }} --set-ctrl=focus_auto=0
        v4l2-ctl -d {{ item }} --set-ctrl=focus_absolute=0
      with_items:
        - /dev/video0
        - /dev/video2
      when:
        - ansible_fqdn == "watcher01.labs.elysianskies.com"

    - name: start rtsp streams
      shell: |
        nohup v4l2rtspserver \
          -P {{ item.port }} -p {{ item.port }} \
          -U {{ item.username }}:{{ item.password }} \
          -W 640 -H 480 \
          -u {{ item.name }} {{ item.device }} &
      no_log: true
      with_items:
        - name: doorway
          port: '8554'
          username: "{{ watcher_username }}"
          password: "{{ watcher_password }}"
          device: /dev/video0
        - name: dining
          port: '8555'
          username: "{{ watcher_username }}"
          password: "{{ watcher_password }}"
          device: /dev/video2
      when:
        - ansible_fqdn == "watcher01.labs.elysianskies.com"

    - name: configure webcams
      shell: |
        v4l2-ctl -d {{ item }} --set-ctrl=led1_mode=0
        v4l2-ctl -d {{ item }} --set-ctrl=sharpness=255
        v4l2-ctl -d {{ item }} --set-ctrl=focus_auto=0
        v4l2-ctl -d {{ item }} --set-ctrl=focus_absolute=0
      with_items:
        - /dev/video0
        - /dev/video2
      when:
        - ansible_fqdn == "watcher02.labs.elysianskies.com"

    - name: start rtsp streams
      shell: |
        nohup v4l2rtspserver \
          -P {{ item.port }} -p {{ item.port }} \
          -U {{ item.username }}:{{ item.password }} \
          -W 640 -H 480 \
          -u {{ item.name }} {{ item.device }} &
      no_log: true
      with_items:
        - name: safe
          port: '8554'
          username: "{{ watcher_username }}"
          password: "{{ watcher_password }}"
          device: /dev/video0
        - name: office
          port: '8555'
          username: "{{ watcher_username }}"
          password: "{{ watcher_password }}"
          device: /dev/video2
      when:
        - ansible_fqdn == "watcher02.labs.elysianskies.com"
