ECHO_TYPE='bold'

if [ "${ECHO_TYPE}" == 'bold' ]; then ECHO_START='\033['
elif [ "${ECHO_TYPE}" == 'regular' ]; then ECHO_START='\e['
fi

ECHO_WHITE="${ECHO_START}1;37m"
ECHO_BLUE="${ECHO_START}1;34m"
ECHO_GREEN="${ECHO_START}1;32m"
ECHO_CYAN="${ECHO_START}1;36m"
ECHO_RED="${ECHO_START}1;31m"
ECHO_PURPLE="${ECHO_START}1;35m"
ECHO_YELLOW="${ECHO_START}1;33m"
ECHO_DARKGRAY="${ECHO_START}1;30m"
ECHO_LIGHTGRAY="${ECHO_START}0;37m"
ECHO_RESET="${ECHO_START}0m"

if [ "${SHELL_STDOUT_COLOR}" == 'white' ]; then SHELL_STDOUT_CODE=$ECHO_WHITE
elif [ "${SHELL_STDOUT_COLOR}" == 'blue' ]; then SHELL_STDOUT_CODE=$ECHO_BLUE
elif [ "${SHELL_STDOUT_COLOR}" == 'green' ]; then SHELL_STDOUT_CODE=$ECHO_GREEN
elif [ "${SHELL_STDOUT_COLOR}" == 'cyan' ]; then SHELL_STDOUT_CODE=$ECHO_CYAN
elif [ "${SHELL_STDOUT_COLOR}" == 'red' ]; then SHELL_STDOUT_CODE=$ECHO_RED
elif [ "${SHELL_STDOUT_COLOR}" == 'purple' ]; then SHELL_STDOUT_CODE=$ECHO_PURPLE
elif [ "${SHELL_STDOUT_COLOR}" == 'yellow' ]; then SHELL_STDOUT_CODE=$ECHO_YELLOW
elif [ "${SHELL_STDOUT_COLOR}" == 'darkgray' ]; then SHELL_STDOUT_CODE=$ECHO_DARKGRAY
elif [ "${SHELL_STDOUT_COLOR}" == 'lightgray' ]; then SHELL_STDOUT_CODE=$ECHO_LIGHTGRAY
fi

if [ "${SHELL_STDERR_COLOR}" == 'white' ]; then SHELL_STDERR_CODE=$ECHO_WHITE
elif [ "${SHELL_STDERR_COLOR}" == 'blue' ]; then SHELL_STDERR_CODE=$ECHO_BLUE
elif [ "${SHELL_STDERR_COLOR}" == 'green' ]; then SHELL_STDERR_CODE=$ECHO_GREEN
elif [ "${SHELL_STDERR_COLOR}" == 'cyan' ]; then SHELL_STDERR_CODE=$ECHO_CYAN
elif [ "${SHELL_STDERR_COLOR}" == 'red' ]; then SHELL_STDERR_CODE=$ECHO_RED
elif [ "${SHELL_STDERR_COLOR}" == 'purple' ]; then SHELL_STDERR_CODE=$ECHO_PURPLE
elif [ "${SHELL_STDERR_COLOR}" == 'yellow' ]; then SHELL_STDERR_CODE=$ECHO_YELLOW
elif [ "${SHELL_STDERR_COLOR}" == 'darkgray' ]; then SHELL_STDERR_CODE=$ECHO_DARKGRAY
elif [ "${SHELL_STDERR_COLOR}" == 'lightgray' ]; then SHELL_STDERR_CODE=$ECHO_LIGHTGRAY
fi

if [ "${SHELL_USER_PROMPT_COLOR}" == 'white' ]; then SHELL_USER_PROMPT_CODE=$ECHO_WHITE
elif [ "${SHELL_USER_PROMPT_COLOR}" == 'blue' ]; then SHELL_USER_PROMPT_CODE=$ECHO_BLUE
elif [ "${SHELL_USER_PROMPT_COLOR}" == 'green' ]; then SHELL_USER_PROMPT_CODE=$ECHO_GREEN
elif [ "${SHELL_USER_PROMPT_COLOR}" == 'cyan' ]; then SHELL_USER_PROMPT_CODE=$ECHO_CYAN
elif [ "${SHELL_USER_PROMPT_COLOR}" == 'red' ]; then SHELL_USER_PROMPT_CODE=$ECHO_RED
elif [ "${SHELL_USER_PROMPT_COLOR}" == 'purple' ]; then SHELL_USER_PROMPT_CODE=$ECHO_PURPLE
elif [ "${SHELL_USER_PROMPT_COLOR}" == 'yellow' ]; then SHELL_USER_PROMPT_CODE=$ECHO_YELLOW
elif [ "${SHELL_USER_PROMPT_COLOR}" == 'darkgray' ]; then SHELL_USER_PROMPT_CODE=$ECHO_DARKGRAY
elif [ "${SHELL_USER_PROMPT_COLOR}" == 'lightgray' ]; then SHELL_USER_PROMPT_CODE=$ECHO_LIGHTGRAY
fi

if [ "${SHELL_HOST_PROMPT_COLOR}" == 'white' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_WHITE
elif [ "${SHELL_HOST_PROMPT_COLOR}" == 'blue' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_BLUE
elif [ "${SHELL_HOST_PROMPT_COLOR}" == 'green' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_GREEN
elif [ "${SHELL_HOST_PROMPT_COLOR}" == 'cyan' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_CYAN
elif [ "${SHELL_HOST_PROMPT_COLOR}" == 'red' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_RED
elif [ "${SHELL_HOST_PROMPT_COLOR}" == 'purple' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_PURPLE
elif [ "${SHELL_HOST_PROMPT_COLOR}" == 'yellow' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_YELLOW
elif [ "${SHELL_HOST_PROMPT_COLOR}" == 'darkgray' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_DARKGRAY
elif [ "${SHELL_HOST_PROMPT_COLOR}" == 'lightgray' ]; then SHELL_HOST_PROMPT_CODE=$ECHO_LIGHTGRAY
fi

if [ "${SHELL_CWD_PROMPT_COLOR}" == 'white' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_WHITE
elif [ "${SHELL_CWD_PROMPT_COLOR}" == 'blue' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_BLUE
elif [ "${SHELL_CWD_PROMPT_COLOR}" == 'green' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_GREEN
elif [ "${SHELL_CWD_PROMPT_COLOR}" == 'cyan' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_CYAN
elif [ "${SHELL_CWD_PROMPT_COLOR}" == 'red' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_RED
elif [ "${SHELL_CWD_PROMPT_COLOR}" == 'purple' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_PURPLE
elif [ "${SHELL_CWD_PROMPT_COLOR}" == 'yellow' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_YELLOW
elif [ "${SHELL_CWD_PROMPT_COLOR}" == 'darkgray' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_DARKGRAY
elif [ "${SHELL_CWD_PROMPT_COLOR}" == 'lightgray' ]; then SHELL_CWD_PROMPT_CODE=$ECHO_LIGHTGRAY
fi
